### ISSUE TITLE
base url status: application error. ubah ke github aja?

### ISSUE THREAD

**Issue by lakuapik** [deriidf/quran-audio_api#1]
Halo bung, 

Projeknya keren, tapi kok pas saya akses base_url nya statusnya: Application Error.

![image](https://user-images.githubusercontent.com/20186786/79746925-fdee1c80-8334-11ea-8edd-611dbbd3acef.png)

Saran, mending ubah base url di readme langsung ke github aja gimana bung? langsung akses raw contentnya seperti ini:

https://github.com/penggguna/QuranJSON/raw/master/surah/1.json

atau

https://raw.githubusercontent.com/penggguna/QuranJSON/master/surah/1.json

Jadi utk akses api tidak usah ke service yang ada di heroku, pakai raw github langsung.

**Comment by penggguna** [comment]
Halo juga,
Makasih sarannya. saya langsung implementasikan.
